/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {
  Platform,
  ImageBackground,
  StyleSheet,
  Text,
  View,
  StatusBar,
} from 'react-native';
import ChatModule, {ChatPlugin} from 'react-native-chat-plugin';

//const chat_url = 'http://ec2-54-244-141-144.us-west-2.compute.amazonaws.com';
const chat_url = 'http://192.168.1.45:3000/';
//const chat_url = 'https://chat.wevive.co.uk/';

const token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjEyNTM4MDQxLCJqdGkiOiI0YWM1YjU4NzdiZTg0Mjk5OTE5OWY4MmI5YTA3MzgzOSIsInVzZXJfaWQiOiJtc3Ryb2tpbkBnbWFpbC5jb20ifQ.VTUNyD0CYDmGVYAgIebgwZAYCsVL_m9nc54lIGjBEpY';
const wetalk_logo = require('./wetalk_logo.png');
export default class App extends Component {
  state = {
    status: 'starting',
    message: '--',
  };
  render() {
    return (
      <View style={styles.chatContainer}>
        <StatusBar translucent backgroundColor="transparent" />
        <View style={styles.headerContainer}>
          <ImageBackground
            source={wetalk_logo}
            style={styles.logo}
            resizeMode="contain"
          />
        </View>
        <ChatModule socketIoUrl={chat_url} options={{token}} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  chatContainer: {
    flex: 1,
    paddingTop: 15,
    backgroundColor: "rgb(241,242,246)",
  },
  logo: {
    width: 150,
    height: 40,
    alignSelf: "center",
  },
  headerContainer: {
    justifyContent: "center",
    alignContent: "center",
    backgroundColor: "rgb(241,242,246)",
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    height: 100,
    width: '100%',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
