export default getFlag = (country) => {
  //  return require('./src/images/countries/' + country + '.png');
  switch (country) {
    case 'BD':
      return require("./src/images/countries/bd.png");
    case 'BE':
      return require("./src/images/countries/be.png");
    case 'BF':
      return require("./src/images/countries/bf.png");
    case 'BG':
      return require("./src/images/countries/bg.png");
    case 'BA':
      return require("./src/images/countries/ba.png");
    case 'BB':
      return require("./src/images/countries/bb.png");
    case 'WF':
      return require("./src/images/countries/wf.png");
    case 'BL':
      return require("./src/images/countries/bl.png");
    case 'BM':
      return require("./src/images/countries/bm.png");
    case 'BN':
      return require("./src/images/countries/bn.png");
    case 'BO':
      return require("./src/images/countries/bo.png");
    case 'BH':
      return require("./src/images/countries/bh.png");
    case 'BI':
      return require("./src/images/countries/bi.png");
    case 'BJ':
      return require("./src/images/countries/bj.png");
    case 'BT':
      return require("./src/images/countries/bt.png");
    case 'JM':
      return require("./src/images/countries/jm.png");
    case 'BV':
      return require("./src/images/countries/bv.png");
    case 'BW':
      return require("./src/images/countries/bw.png");
    case 'WS':
      return require("./src/images/countries/ws.png");
    case 'BQ':
      return require("./src/images/countries/bq.png");
    case 'BR':
      return require("./src/images/countries/br.png");
    case 'BS':
      return require("./src/images/countries/bs.png");
    case 'JE':
      return require("./src/images/countries/je.png");
    case 'BY':
      return require("./src/images/countries/by.png");
    case 'BZ':
      return require("./src/images/countries/bz.png");
    case 'RU':
      return require("./src/images/countries/ru.png");
    case 'RW':
      return require("./src/images/countries/rw.png");
    case 'RS':
      return require("./src/images/countries/rs.png");
    case 'TL':
      return require("./src/images/countries/tl.png");
    case 'RE':
      return require("./src/images/countries/re.png");
    case 'TM':
      return require("./src/images/countries/tm.png");
    case 'TJ':
      return require("./src/images/countries/tj.png");
    case 'RO':
      return require("./src/images/countries/ro.png");
    case 'TK':
      return require("./src/images/countries/tk.png");
    case 'GW':
      return require("./src/images/countries/gw.png");
    case 'GU':
      return require("./src/images/countries/gu.png");
    case 'GT':
      return require("./src/images/countries/gt.png");
    case 'GS':
      return require("./src/images/countries/gs.png");
    case 'GR':
      return require("./src/images/countries/gr.png");
    case 'GQ':
      return require("./src/images/countries/gq.png");
    case 'GP':
      return require("./src/images/countries/gp.png");
    case 'JP':
      return require("./src/images/countries/jp.png");
    case 'GY':
      return require("./src/images/countries/gy.png");
    case 'GG':
      return require("./src/images/countries/gg.png");
    case 'GF':
      return require("./src/images/countries/gf.png");
    case 'GE':
      return require("./src/images/countries/ge.png");
    case 'GD':
      return require("./src/images/countries/gd.png");
    case 'GB':
      return require("./src/images/countries/gb.png");
    case 'GA':
      return require("./src/images/countries/ga.png");
    case 'SV':
      return require("./src/images/countries/sv.png");
    case 'GN':
      return require("./src/images/countries/gn.png");
    case 'GM':
      return require("./src/images/countries/gm.png");
    case 'GL':
      return require("./src/images/countries/gl.png");
    case 'GI':
      return require("./src/images/countries/gi.png");
    case 'GH':
      return require("./src/images/countries/gh.png");
    case 'OM':
      return require("./src/images/countries/om.png");
    case 'TN':
      return require("./src/images/countries/tn.png");
    case 'JO':
      return require("./src/images/countries/jo.png");
    case 'HR':
      return require("./src/images/countries/hr.png");
    case 'HT':
      return require("./src/images/countries/ht.png");
    case 'HU':
      return require("./src/images/countries/hu.png");
    case 'HK':
      return require("./src/images/countries/hk.png");
    case 'HN':
      return require("./src/images/countries/hn.png");
    case 'HM':
      return require("./src/images/countries/hm.png");
    case 'VE':
      return require("./src/images/countries/ve.png");
    case 'PR':
      return require("./src/images/countries/pr.png");
    case 'PS':
      return require("./src/images/countries/ps.png");
    case 'PW':
      return require("./src/images/countries/pw.png");
    case 'PT':
      return require("./src/images/countries/pt.png");
    case 'SJ':
      return require("./src/images/countries/sj.png");
    case 'PY':
      return require("./src/images/countries/py.png");
    case 'IQ':
      return require("./src/images/countries/iq.png");
    case 'PA':
      return require("./src/images/countries/pa.png");
    case 'PF':
      return require("./src/images/countries/pf.png");
    case 'PG':
      return require("./src/images/countries/pg.png");
    case 'PE':
      return require("./src/images/countries/pe.png");
    case 'PK':
      return require("./src/images/countries/pk.png");
    case 'PH':
      return require("./src/images/countries/ph.png");
    case 'PN':
      return require("./src/images/countries/pn.png");
    case 'PL':
      return require("./src/images/countries/pl.png");
    case 'PM':
      return require("./src/images/countries/pm.png");
    case 'ZM':
      return require("./src/images/countries/zm.png");
    case 'EH':
      return require("./src/images/countries/eh.png");
    case 'EE':
      return require("./src/images/countries/ee.png");
    case 'EG':
      return require("./src/images/countries/eg.png");
    case 'ZA':
      return require("./src/images/countries/za.png");
    case 'EC':
      return require("./src/images/countries/ec.png");
    case 'IT':
      return require("./src/images/countries/it.png");
    case 'VN':
      return require("./src/images/countries/vn.png");
    case 'SB':
      return require("./src/images/countries/sb.png");
    case 'ET':
      return require("./src/images/countries/et.png");
    case 'SO':
      return require("./src/images/countries/so.png");
    case 'ZW':
      return require("./src/images/countries/zw.png");
    case 'SA':
      return require("./src/images/countries/sa.png");
    case 'ES':
      return require("./src/images/countries/es.png");
    case 'ER':
      return require("./src/images/countries/er.png");
    case 'ME':
      return require("./src/images/countries/me.png");
    case 'MD':
      return require("./src/images/countries/md.png");
    case 'MG':
      return require("./src/images/countries/mg.png");
    case 'MF':
      return require("./src/images/countries/mf.png");
    case 'MA':
      return require("./src/images/countries/ma.png");
    case 'MC':
      return require("./src/images/countries/mc.png");
    case 'UZ':
      return require("./src/images/countries/uz.png");
    case 'MM':
      return require("./src/images/countries/mm.png");
    case 'ML':
      return require("./src/images/countries/ml.png");
    case 'MO':
      return require("./src/images/countries/mo.png");
    case 'MN':
      return require("./src/images/countries/mn.png");
    case 'MH':
      return require("./src/images/countries/mh.png");
    case 'MK':
      return require("./src/images/countries/mk.png");
    case 'MU':
      return require("./src/images/countries/mu.png");
    case 'MT':
      return require("./src/images/countries/mt.png");
    case 'MW':
      return require("./src/images/countries/mw.png");
    case 'MV':
      return require("./src/images/countries/mv.png");
    case 'MQ':
      return require("./src/images/countries/mq.png");
    case 'MP':
      return require("./src/images/countries/mp.png");
    case 'MS':
      return require("./src/images/countries/ms.png");
    case 'MR':
      return require("./src/images/countries/mr.png");
    case 'IM':
      return require("./src/images/countries/im.png");
    case 'UG':
      return require("./src/images/countries/ug.png");
    case 'TZ':
      return require("./src/images/countries/tz.png");
    case 'MY':
      return require("./src/images/countries/my.png");
    case 'MX':
      return require("./src/images/countries/mx.png");
    case 'IL':
      return require("./src/images/countries/il.png");
    case 'FR':
      return require("./src/images/countries/fr.png");
    case 'IO':
      return require("./src/images/countries/io.png");
    case 'SH':
      return require("./src/images/countries/sh.png");
    case 'FI':
      return require("./src/images/countries/fi.png");
    case 'FJ':
      return require("./src/images/countries/fj.png");
    case 'FK':
      return require("./src/images/countries/fk.png");
    case 'FM':
      return require("./src/images/countries/fm.png");
    case 'FO':
      return require("./src/images/countries/fo.png");
    case 'NI':
      return require("./src/images/countries/ni.png");
    case 'NL':
      return require("./src/images/countries/nl.png");
    case 'NO':
      return require("./src/images/countries/no.png");
    case 'NA':
      return require("./src/images/countries/na.png");
    case 'VU':
      return require("./src/images/countries/vu.png");
    case 'NC':
      return require("./src/images/countries/nc.png");
    case 'NE':
      return require("./src/images/countries/ne.png");
    case 'NF':
      return require("./src/images/countries/nf.png");
    case 'NG':
      return require("./src/images/countries/ng.png");
    case 'NZ':
      return require("./src/images/countries/nz.png");
    case 'NP':
      return require("./src/images/countries/np.png");
    case 'NR':
      return require("./src/images/countries/nr.png");
    case 'NU':
      return require("./src/images/countries/nu.png");
    case 'CK':
      return require("./src/images/countries/ck.png");
    case 'XK':
      return require("./src/images/countries/xk.png");
    case 'CI':
      return require("./src/images/countries/ci.png");
    case 'CH':
      return require("./src/images/countries/ch.png");
    case 'CO':
      return require("./src/images/countries/co.png");
    case 'CN':
      return require("./src/images/countries/cn.png");
    case 'CM':
      return require("./src/images/countries/cm.png");
    case 'CL':
      return require("./src/images/countries/cl.png");
    case 'CC':
      return require("./src/images/countries/cc.png");
    case 'CA':
      return require("./src/images/countries/ca.png");
    case 'CG':
      return require("./src/images/countries/cg.png");
    case 'CF':
      return require("./src/images/countries/cf.png");
    case 'CD':
      return require("./src/images/countries/cd.png");
    case 'CZ':
      return require("./src/images/countries/cz.png");
    case 'CY':
      return require("./src/images/countries/cy.png");
    case 'CX':
      return require("./src/images/countries/cx.png");
    case 'CR':
      return require("./src/images/countries/cr.png");
    case 'CW':
      return require("./src/images/countries/cw.png");
    case 'CV':
      return require("./src/images/countries/cv.png");
    case 'CU':
      return require("./src/images/countries/cu.png");
    case 'SZ':
      return require("./src/images/countries/sz.png");
    case 'SY':
      return require("./src/images/countries/sy.png");
    case 'SX':
      return require("./src/images/countries/sx.png");
    case 'KG':
      return require("./src/images/countries/kg.png");
    case 'KE':
      return require("./src/images/countries/ke.png");
    case 'SS':
      return require("./src/images/countries/ss.png");
    case 'SR':
      return require("./src/images/countries/sr.png");
    case 'KI':
      return require("./src/images/countries/ki.png");
    case 'KH':
      return require("./src/images/countries/kh.png");
    case 'KN':
      return require("./src/images/countries/kn.png");
    case 'KM':
      return require("./src/images/countries/km.png");
    case 'ST':
      return require("./src/images/countries/st.png");
    case 'SK':
      return require("./src/images/countries/sk.png");
    case 'KR':
      return require("./src/images/countries/kr.png");
    case 'SI':
      return require("./src/images/countries/si.png");
    case 'KP':
      return require("./src/images/countries/kp.png");
    case 'KW':
      return require("./src/images/countries/kw.png");
    case 'SN':
      return require("./src/images/countries/sn.png");
    case 'SM':
      return require("./src/images/countries/sm.png");
    case 'SL':
      return require("./src/images/countries/sl.png");
    case 'SC':
      return require("./src/images/countries/sc.png");
    case 'KZ':
      return require("./src/images/countries/kz.png");
    case 'KY':
      return require("./src/images/countries/ky.png");
    case 'SG':
      return require("./src/images/countries/sg.png");
    case 'SE':
      return require("./src/images/countries/se.png");
    case 'SD':
      return require("./src/images/countries/sd.png");
    case 'DO':
      return require("./src/images/countries/do.png");
    case 'DM':
      return require("./src/images/countries/dm.png");
    case 'DJ':
      return require("./src/images/countries/dj.png");
    case 'DK':
      return require("./src/images/countries/dk.png");
    case 'VG':
      return require("./src/images/countries/vg.png");
    case 'DE':
      return require("./src/images/countries/de.png");
    case 'YE':
      return require("./src/images/countries/ye.png");
    case 'DZ':
      return require("./src/images/countries/dz.png");
    case 'US':
      return require("./src/images/countries/us.png");
    case 'UY':
      return require("./src/images/countries/uy.png");
    case 'YT':
      return require("./src/images/countries/yt.png");
    case 'UM':
      return require("./src/images/countries/um.png");
    case 'LB':
      return require("./src/images/countries/lb.png");
    case 'LC':
      return require("./src/images/countries/lc.png");
    case 'LA':
      return require("./src/images/countries/la.png");
    case 'TV':
      return require("./src/images/countries/tv.png");
    case 'TW':
      return require("./src/images/countries/tw.png");
    case 'TT':
      return require("./src/images/countries/tt.png");
    case 'TR':
      return require("./src/images/countries/tr.png");
    case 'LK':
      return require("./src/images/countries/lk.png");
    case 'LI':
      return require("./src/images/countries/li.png");
    case 'LV':
      return require("./src/images/countries/lv.png");
    case 'TO':
      return require("./src/images/countries/to.png");
    case 'LT':
      return require("./src/images/countries/lt.png");
    case 'LU':
      return require("./src/images/countries/lu.png");
    case 'LR':
      return require("./src/images/countries/lr.png");
    case 'LS':
      return require("./src/images/countries/ls.png");
    case 'TH':
      return require("./src/images/countries/th.png");
    case 'TF':
      return require("./src/images/countries/tf.png");
    case 'TG':
      return require("./src/images/countries/tg.png");
    case 'TD':
      return require("./src/images/countries/td.png");
    case 'TC':
      return require("./src/images/countries/tc.png");
    case 'LY':
      return require("./src/images/countries/ly.png");
    case 'VA':
      return require("./src/images/countries/va.png");
    case 'VC':
      return require("./src/images/countries/vc.png");
    case 'AE':
      return require("./src/images/countries/ae.png");
    case 'AD':
      return require("./src/images/countries/ad.png");
    case 'AG':
      return require("./src/images/countries/ag.png");
    case 'AF':
      return require("./src/images/countries/af.png");
    case 'AI':
      return require("./src/images/countries/ai.png");
    case 'VI':
      return require("./src/images/countries/vi.png");
    case 'IS':
      return require("./src/images/countries/is.png");
    case 'IR':
      return require("./src/images/countries/ir.png");
    case 'AM':
      return require("./src/images/countries/am.png");
    case 'AL':
      return require("./src/images/countries/al.png");
    case 'AO':
      return require("./src/images/countries/ao.png");
    case 'AQ':
      return require("./src/images/countries/aq.png");
    case 'AS':
      return require("./src/images/countries/as.png");
    case 'AR':
      return require("./src/images/countries/ar.png");
    case 'AU':
      return require("./src/images/countries/au.png");
    case 'AT':
      return require("./src/images/countries/at.png");
    case 'AW':
      return require("./src/images/countries/aw.png");
    case 'IN':
      return require("./src/images/countries/in.png");
    case 'AX':
      return require("./src/images/countries/ax.png");
    case 'AZ':
      return require("./src/images/countries/az.png");
    case 'IE':
      return require("./src/images/countries/ie.png");
    case 'ID':
      return require("./src/images/countries/id.png");
    case 'UA':
      return require("./src/images/countries/ua.png");
    case 'QA':
      return require("./src/images/countries/qa.png");
    case 'MZ':
      return require("./src/images/countries/mz.png");
  }
}