
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
install! 'cocoapods', :deterministic_uuids => false
workspace 'jitsi-meet'
platform :ios, '11.0'
pre_install do |installer|
  def installer.verify_no_static_framework_transitive_dependencies; end
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
      def pod.build_type;
        Pod::BuildType.static_library # >= 1.9
      end
    end
  end
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
target 'JitsiMeetSDK' do
  project 'sdk/sdk.xcodeproj'

  #use_react_native!(:path => config["reactNativePath"])
  pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector/'
  pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec/'
  pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired/'
  pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety/'
  pod 'React', :path => '../node_modules/react-native/'
  pod 'ReactCommon', :path => '../node_modules/react-native/ReactCommon', :subspecs => [
    'turbomodule'
  ]
  pod 'React-Core', :path => '../node_modules/react-native/', :subspecs => [
    'CoreModulesHeaders',
    'DevSupport',
    'RCTWebSocket'
  ]
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  #pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'
  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  #pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  #pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  #pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNWatch', :path => '../node_modules/react-native-watch-connectivity'
  pod 'RNDefaultPreference', :path => '../node_modules/react-native-default-preference'


  #pod 'GoogleSignIn', '~> 5.0.2'

  # Native pod dependencies
  #

  pod 'CocoaLumberjack', '~>3.5.3'
  #pod 'ObjectiveDropboxOfficial', '~> 3.9.4'

  use_native_modules!

end
target 'JitsiMeet' do
  project 'app/app.xcodeproj'
  config = use_native_modules!

  # add the Firebase pod for Google Analytics
  pod 'Firebase/CoreOnly'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/DynamicLinks'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods


end

post_install do |installer|
  #flipper_post_install(installer)
  #system(". ./pod_post_install.sh")
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      #config.build_settings['SWIFT_VERSION'] = '5.0'  # required by simple_permission
      #config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SUPPORTS_MACCATALYST'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
